Repository matheusmigge/did-i-floss, pull requests merged in 2024-01, with the labels that each got.

#3 homeScreenView
  DidIFloss.xcodeproj/project.pbxproj
  DidIFloss.xcodeproj/project.xcworkspace/xcuserdata/Migge.xcuserdatad/UserInterfaceState.xcuserstate
  DidIFloss/Assets.xcassets/Colors/Contents.json
  DidIFloss/Assets.xcassets/Colors/flamingo-pink.colorset/Contents.json
  DidIFloss/Assets.xcassets/Colors/greeny-blue.colorset/Contents.json
  DidIFloss/Assets.xcassets/Colors/light-yellow.colorset/Contents.json
  DidIFloss/Assets.xcassets/Colors/sky-blue.colorset/Contents.json
  DidIFloss/Assets.xcassets/Images/Contents.json
  DidIFloss/Assets.xcassets/Images/pink-tooth.imageset/Contents.json
  DidIFloss/Assets.xcassets/Images/pink-tooth.imageset/teeth pink.png
  DidIFloss/Assets.xcassets/Images/yellow-tooth.imageset/Contents.json
  DidIFloss/Assets.xcassets/Images/yellow-tooth.imageset/teeth yellow.png
  DidIFloss/Constants.swift
  DidIFloss/DidIFlossApp.swift
  DidIFloss/Fonts/Borel-Regular.ttf
  DidIFloss/Info.plist
  DidIFloss/ViewModels/ContentViewModel.swift
  DidIFloss/Views/Components/ToothView.swift
  DidIFloss/Views/ContentView.swift
  DidIFloss/Views/HomeScreenView.swift
Labels: enhancement

#4 Create .gitignore
  .gitignore
Labels: documentation, enhancement

#5 background layout
  DidIFloss.xcodeproj/project.pbxproj
  DidIFloss.xcodeproj/project.xcworkspace/xcuserdata/Migge.xcuserdatad/UserInterfaceState.xcuserstate
  DidIFloss/Assets.xcassets/AppIcon.appiconset/Contents.json
  DidIFloss/Assets.xcassets/AppIcon.appiconset/icone.png
  DidIFloss/Assets.xcassets/Images/pink-tooth.imageset/Contents.json
  DidIFloss/Assets.xcassets/Images/pink-tooth.imageset/pink-tooth.png
  DidIFloss/Assets.xcassets/Images/pink-tooth.imageset/teeth pink.png
  DidIFloss/Assets.xcassets/Images/yellow-tooth.imageset/Contents.json
  DidIFloss/Assets.xcassets/Images/yellow-tooth.imageset/teeth yellow.png
  DidIFloss/Assets.xcassets/Images/yellow-tooth.imageset/yellow-tooth.png
  DidIFloss/Views/Components/BackgroundView.swift
  DidIFloss/Views/Components/ToothView.swift
  DidIFloss/Views/HomeScreenView.swift
Labels: enhancement

#7 Fix/refactoring floss record
  DidIFloss.xcodeproj/project.pbxproj
  DidIFloss/Service/Persistence/FlossRecordDataSouce.swift
  DidIFloss/Service/Persistence/FlossRecordDataSource.swift
  DidIFloss/Service/Persistence/PersistanceManager.swift
  DidIFloss/Service/Persistence/PersistenceManager+KEYS.swift
  DidIFloss/Service/Persistence/Protocols/FlossRecordDataProvider.swift
  DidIFloss/Service/Persistence/Protocols/PersistenceManagerProtocol.swift
  DidIFloss/Service/Persistence/Protocols/UserDefaults+Protocol.swift
Labels: documentation

#8 Content view layout
  DidIFloss.xcodeproj/project.pbxproj
  DidIFloss.xcodeproj/project.xcworkspace/xcuserdata/Migge.xcuserdatad/UserInterfaceState.xcuserstate
  DidIFloss/Views/ContentView.swift
  DidIFloss/Views/HomeScreenView.swift
Labels: enhancement

#9 Fix/refactoring floss record
  DidIFloss.xcodeproj/project.pbxproj
  DidIFloss/Service/Persistence/FlossRecordDataSource.swift
  DidIFloss/Service/Persistence/PersistanceManager.swift
  DidIFloss/Service/Persistence/Protocols/FlossRecordDataProvider.swift
  DidIFloss/Service/Persistence/Protocols/PersistenceManagerProtocol.swift
  DidIFloss/Service/Persistence/Protocols/UserDefaults+Protocol.swift
  DidIFloss/ViewModels/ContentViewModel.swift
Labels: documentation, enhancement

#12 Feature/calendar view
  DidIFloss.xcodeproj/project.pbxproj
  DidIFloss/Extensions/Calendar.swift
  DidIFloss/Extensions/Date.swift
  DidIFloss/Views/Components/CalendarView.swift
  NotificationService/Sources/NotificationService/NotificationService.swift
Labels: enhancement
